kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:1
  commands:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all

- name: registry_deploy  
  image: plugins/docker
  settings:
    registry: drone.tuckerthomas.com:5000
    username: tthomas
    password: test
    repo: drone.tuckerthomas.com:5000/kekw
    insecure: true
    dockerfile: Dockerfile
    tags: "0.1"
    