kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:1
  commands:
  - cargo build --release --verbose --all
  - cargo test --release --verbose --all

- name: registry_deploy  
  image: plugins/docker
  settings:
    registry: registry.tuckerthomas.com
    username: tthomas
    password: test
    repo: registry.tuckerthomas.com/kekw
    insecure: true
    dockerfile: Dockerfile
    tags: "0.1"