kind: pipeline
type: docker
name: default

steps:
- name: test
  image: rust:1
  commands:
  - cargo build --release --verbose --all
  - cargo test --verbose --all

- name: docker  
  image: plugins/docker
  settings:
    username: tthomas
    password: test
    repo: localhost:5000
    dockerfile: Dockerfile